;;; Generated by Verrazano 0.5 Then Heavily editted :)

(cffi:defcfun ("SOIL_load_OGL_texture" soil-load-ogl-texture) :unsigned-int
  (filename :pointer)
  (force-channels :int)
  (reuse-texture-id :unsigned-int)
  (flags ogl-texture-flags))

(cffi:defcfun ("SOIL_create_OGL_texture" soil-create-ogl-texture) 
    :unsigned-int
  (data :pointer)
  (width :int)
  (height :int)
  (channels :int)
  (reuse-texture-id :unsigned-int)
  (flags :unsigned-int))

(cffi:defcenum ogl-texture-flags
  (:soil-flag-power-of-two 1)
  (:soil-flag-mipmaps 2)
  (:soil-flag-texture-repeats 4)
  (:soil-flag-multiply-alpha 8)
  (:soil-flag-invert-y 16)
  (:soil-flag-compress-to-dxt 32)
  (:soil-flag-dds-load-direct 64)
  (:soil-flag-ntsc-safe-rgb 128)
  (:soil-flag-co-cg-y 256)
  (:soil-flag-texture-rectangle 512))

(cffi:defcenum savable-image-types-enum
  (:soil-save-type-tga 0)
  (:soil-save-type-bmp 1)
  (:soil-save-type-dds 2))

(cffi:defcfun ("SOIL_load_OGL_single_cubemap_from_memory" 
               soil-load-ogl-single-cubemap-from-memory) :unsigned-int
  (buffer :pointer)
  (buffer-length :int)
  (face-order :pointer)
  (force-channels :int)
  (reuse-texture-id :unsigned-int)
  (flags :unsigned-int))

(cffi:defcfun ("SOIL_save_screenshot" soil-save-screenshot) :int
  (filename :pointer)
  (image-type :int)
  (x :int)
  (y :int)
  (width :int)
  (height :int))

(cffi:defcfun ("SOIL_load_OGL_single_cubemap" 
               soil-load-ogl-single-cubemap) :unsigned-int
  (filename :pointer)
  (face-order :pointer)
  (force-channels :int)
  (reuse-texture-id :unsigned-int)
  (flags :unsigned-int))

(cffi:defcfun ("SOIL_last_result" soil-last-result) :pointer)

(cffi:defcfun ("SOIL_load_image_from_memory" 
               soil-load-image-from-memory) (:pointer :unsigned-char)
  (buffer :pointer)
  (buffer-length :int)
  (width (:pointer :int))
  (height (:pointer :int))
  (channels (:pointer :int))
  (force-channels :int))

(cffi:defcfun ("SOIL_load_OGL_cubemap_from_memory"
               soil-load-ogl-cubemap-from-memory) :unsigned-int
  (x-pos-buffer :pointer)
  (x-pos-buffer-length :int)
  (x-neg-buffer :pointer)
  (x-neg-buffer-length :int)
  (y-pos-buffer :pointer)
  (y-pos-buffer-length :int)
  (y-neg-buffer :pointer)
  (y-neg-buffer-length :int)
  (z-pos-buffer :pointer)
  (z-pos-buffer-length :int)
  (z-neg-buffer :pointer)
  (z-neg-buffer-length :int)
  (force-channels :int)
  (reuse-texture-id :unsigned-int)
  (flags :unsigned-int))

(cffi:defcfun ("SOIL_create_OGL_single_cubemap" 
               soil-create-ogl-single-cubemap) :unsigned-int
  (data :pointer)
  (width :int)
  (height :int)
  (channels :int)
  (face-order :pointer)
  (reuse-texture-id :unsigned-int)
  (flags :unsigned-int))

(cffi:defcenum image-format-enum
  (:soil-load-auto 0)
  (:soil-load-l 1)
  (:soil-load-la 2)
  (:soil-load-rgb 3)
  (:soil-load-rgba 4))

(cffi:defcenum reuse-enum
  (:soil-create-new-id 0))

(cffi:defcenum hdr-enum
  (:soil-hdr-rgbe 0)
  (:soil-hdr-rg-bdiv-a 1)
  (:soil-hdr-rg-bdiv-a-2 2))

(cffi:defcfun ("SOIL_load_image" soil-load-image) (:pointer :unsigned-char)
  (filename :pointer)
  (width (:pointer :int))
  (height (:pointer :int))
  (channels (:pointer :int))
  (force-channels :int))

(cffi:defcfun ("SOIL_save_image" soil-save-image) :int (filename :pointer)
              (image-type :int)
              (width :int)
              (height :int)
              (channels :int)
              (data :pointer))

(cffi:defcfun ("SOIL_load_OGL_HDR_texture" 
               soil-load-ogl-hdr-texture) :unsigned-int
  (filename :pointer)
  (fake-hdr-format :int)
  (rescale-to-max :int)
  (reuse-texture-id :unsigned-int)
  (flags :unsigned-int))

(cffi:defcfun ("SOIL_load_OGL_cubemap" soil-load-ogl-cubemap) :unsigned-int
  (x-pos-file :pointer)
  (x-neg-file :pointer)
  (y-pos-file :pointer)
  (y-neg-file :pointer)
  (z-pos-file :pointer)
  (z-neg-file :pointer)
  (force-channels :int)
  (reuse-texture-id :unsigned-int)
  (flags :unsigned-int))

